apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "centrifugo.fullname" . }}
  namespace: {{ include "centrifugo.namespace" . }}
  labels:
    {{- include "centrifugo.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "centrifugo.selectorLabels" . | nindent 6 }}
  {{- if .Values.deploymentStrategy }}
  strategy:
    {{ toYaml .Values.deploymentStrategy | indent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "centrifugo.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "centrifugo.imagePullSecrets" . | indent 6 }}
      serviceAccountName: {{ include "centrifugo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "centrifugo.image" .}}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.image.command }}
          command:
            - {{ .Values.image.command }}
          {{- end }}
          args:
            - --health
            - --prometheus
            - --port
            - "{{ .Values.service.port }}"
            - --internal_port
            - "{{ .Values.internalService.port }}"
          env:
            - name: CENTRIFUGO_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "centrifugo.secretName" . }}
                  key: admin_password
            - name: CENTRIFUGO_ADMIN_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "centrifugo.secretName" . }}
                  key: admin_secret
            {{- if .Values.secrets.tokenHmacSecretKey }}
            - name: CENTRIFUGO_TOKEN_HMAC_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "centrifugo.secretName" . }}
                  key: token_hmac_secret_key
            {{- end }}
            {{- if .Values.secrets.apiKey }}
            - name: CENTRIFUGO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "centrifugo.secretName" . }}
                  key: api_key
            {{- end }}
            {{- if .Values.secrets.grpcApiKey }}
            - name: CENTRIFUGO_GRPC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "centrifugo.secretName" . }}
                  key: grpc_api_key
            {{- end }}
            {{- if .Values.secrets.redisAddress }}
            - name: CENTRIFUGO_REDIS_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: {{ include "centrifugo.secretName" . }}
                  key: redis_address
            {{- end }}
            {{- if .Values.secrets.redisCertificateAuthorities }}
            - name: REDIS_CERTIFICATE_AUTHORITIES
              valueFrom:
                secretKeyRef:
                  name: {{ include "centrifugo.secretName" . }}
                  key: redis_certificate_authorities
            {{- end }}
            {{- if .Values.secrets.redisSentinelPassword }}
            - name: CENTRIFUGO_REDIS_SENTINEL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "centrifugo.secretName" . }}
                  key: redis_sentinel_password
            {{- end }}
            {{- if .Values.secrets.natsUrl }}
            - name: CENTRIFUGO_NATS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "centrifugo.secretName" . }}
                  key: nats_url
            {{- end }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - name: external
              containerPort: {{ .Values.service.port }}
            - name: internal
              containerPort: {{ .Values.internalService.port }}
            - name: grpc
              containerPort: {{ .Values.grpcService.port }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.internalService.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.internalService.port }}
            initialDelaySeconds: 3
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
