{{- if .Values.ingress.enabled -}}
{{- $fullName := include "centrifugo.fullname" . -}}
{{- $namespace := include "centrifugo.namespace" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ $namespace }}
  labels:
    {{- include "centrifugo.labels" . | nindent 4 }}
  annotations:
    networking.gke.io/managed-certificates: {{ include "centrifugo.fullname" . }}
    {{ if .Values.managedcertificate.enabled -}}
    kubernetes.io/ingress.class: "gce"
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port: 
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
  {{- end }}
