## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry and imagePullSecrets
##
# global:
#   imageRegistry: myRegistryName
#   imagePullSecrets:
#     - myRegistryKeySecretName

replicaCount: 1

image:
  registry: docker.io
  repository: centrifugo/centrifugo
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  command: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""

service:
  ## Service type
  ##
  type: ClusterIP
  ## Service port
  ##
  port: 8000
  ## Specify the nodePort value for the LoadBalancer and NodePort service types.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
  ##
  nodePort: ""
  ## Provide any additional annotations which may be required
  ##
  annotations: {}
  ##
  ## Use separate service for internal endpoints. It could be useful for configuring same port number for all services.
  useSeparateInternalService: false
  ## Use separate service for GRPC endpoints. It could be useful for configuring same port number for all services.
  useSeparateGrpcService: false

internalService:
  port: 9000
  type: ClusterIP
  nodePort: ""
  # Static NodePort, if set.
  # nodePort: 30101
  annotations: {}
    # prometheus.io/scrape: "true"
    # prometheus.io/path: "/metrics"
    # prometheus.io/port: "9000"

grpcService:
  port: 10000
  type: ClusterIP
  nodePort: ""
  # Static NodePort, if set.
  # nodePort: 30102
  annotations: {}

backendconfig:
  enabled: false

  # Maximum duration websocket connections can stay open.
  # https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#timeout
  timeoutSec: 86400

  # For SockJS connections not using websockets, session affinity is required so the
  # client always gets forwarded to the same Centrifugo pod.
  # https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#session_affinity
  sessionAffinity:
    enabled: false
    affinityType: "GENERATED_COOKIE"
    affinityCookieTtlSec: 3600

managedcertificate:
  enabled: false
  domains: []

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    #
    # To run on custom path:
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts: []
    # - host: centrifugo.local
    #   paths:
    #     - /
    # - host: centrifugo-with-prefix.local
    #   paths:
    #     - /test(/|$)(.*)

resources: {}

serviceAccount:
  # Specifies whether a service account should be created.
  create: true
  # Annotations to add to the service account.
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template.
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

terminationGracePeriodSeconds: 30

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
  #
  # You can also tune sysctl, ex.:
  # sysctls:
  #   - name: net.core.somaxconn
  #     value: "2048"

deploymentStrategy: {}
  # type: RollingUpdate
  # rollingUpdate:
  #   maxSurge: 0
  #   maxUnavailable: 1

metrics:
  enabled: false
  serviceMonitor:
    enabled: false
    ## Specify the namespace in which the serviceMonitor resource will be created
    ##
    # namespace: ""
    ## Specify the interval at which metrics should be scraped
    ##
    interval: 30s
    ## Specify the timeout after which the scrape is ended
    ##
    # scrapeTimeout: 30s
    ## Specify Metric Relabellings to add to the scrape endpoint
    ##
    # relabellings:
    ## Specify honorLabels parameter to add the scrape endpoint
    ##
    honorLabels: false
    ## Specify the release for ServiceMonitor. Sometimes it should be custom for prometheus operator to work
    ##
    # release: ""
    ## Used to pass Labels that are used by the Prometheus installed in your cluster to select Service Monitors to work with
    ## ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#prometheusspec
    ##
    additionalLabels: {}


nodeSelector: {}

tolerations: []

affinity: {}

# Additional environment variables to be passed to Centrifugo container.
env: {}

# existingSecret: my-secret

# Centrifugo secrets.
secrets:
  # Secret key for HMAC tokens.
  tokenHmacSecretKey: ""

  # Admin password used to protect access to web interface.
  adminPassword: ""

  # Admin secret used to create auth tokens on user login into admin web interface.
  adminSecret: ""

  # Centrifugo api_key for Centrifugo API endpoint authorization.
  apiKey: ""

  # Centrifugo grpc_api_key for Centrifugo GRPC API authorization.
  grpcApiKey: ""

  # Connection address for Redis.
  redisAddress: ""

  # Password for Redis Sentinel.
  redisSentinelPassword: ""

  # Connection string to Nats.
  natsUrl: ""
